import Head from "next/head";
import loadingLottieFile from "../../../public/lottie/santa.json";
import * as S from "styles/login";

import KakaoLoginButton from "components/KakaoButton";
import { kakaoInit } from "service";
import { useSetRecoilState } from "recoil";
import { authState, userState } from "stores";

export default function Login() {
  const setAuth = useSetRecoilState(authState);
  const setUser = useSetRecoilState(userState);

  const kakaoLogin = async () => {
    const kakao = kakaoInit();
    kakao.Auth.login({
      success: (res: any) => {
        setAuth({
          accessToken: res.access_token as string,
          refreshToken: res.refresh_token as string,
        });

        kakao.API.request({
          url: "/v2/user/me",
        })
          .then(function (response: any) {
            setUser({
              id: response.id as number,
              nickname: response.kakao_account.profile.nickname as string,
            });
          })
          .catch(function (error: any) {
            console.log(error);
          });
      },
      fail: (error: any) => {
        console.log(error);
      },
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="descriptio0n" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <S.Layout>
        <S.Title type="24-600">나만의 스노우볼을 만들어봐요.</S.Title>

        <S.WaitingLottie loop autoplay animationData={loadingLottieFile} />
        <S.Footer>
          <KakaoLoginButton onClick={() => kakaoLogin()} />
        </S.Footer>
      </S.Layout>
    </>
  );
}
