import { Snowball } from "components";
import { Button } from "components/Button";
import Header from "components/Header";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useRecoilValue, useSetRecoilState } from "recoil";
import { authState, redirectUrlState } from "stores";

import * as S from "styles/home";

export default function Home() {
  const router = useRouter();
  const user = useRecoilValue(authState);
  const setRedirect = useSetRecoilState(redirectUrlState);

  const handlePrimaryButtonClick = () => {
    if (user.accessToken) {
      router.push("/create");
      return;
    }
    setRedirect("/create");
    router.push("/login");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="descriptio0n" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <S.Layout>
        <S.SnowballLayout>
          <S.Title>
            <Image
              src="/images/title.png"
              alt="제목"
              objectFit="contain"
              layout="fill"
              priority
            ></Image>
          </S.Title>
          <Snowball />
        </S.SnowballLayout>
      </S.Layout>
      <S.Footer>
        <Button onClick={handlePrimaryButtonClick}>내 스노우볼 만들기</Button>
        {/* <Button onClick={handlePrimaryButtonClick}>내 스노우볼 보기</Button> */}
      </S.Footer>
    </>
  );
}
