import loadingLottieFile from "../../public/lottie/waiting.json";

import Head from "next/head";

import * as S from "styles/home";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="descriptio0n" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.WaitingLottie loop autoplay animationData={loadingLottieFile} />
    </div>
  );
}
